repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: pretty-format-json
      args:
        - "--autofix"

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args:
        - --line-length=88
        - --include='\.pyi?$'
      language_version: python3.10


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
    - id: mypy
      additional_dependencies:
        - 'sqlalchemy[mypy]'


- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args:
        - "--max-line-length=88"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"
